import React from "react";

export const metadata = {
  title: "Rooms",
  description: "Generated by create next app",
};

export default async function page() {
  return (
    <div>
      <h1 className="text-4xl mb-5 text-teal-300 font-medium">
        Our Luxury Rooms
      </h1>
      <p className="text-gray-300 text-lg mb-10">
        Cozy yet luxurious Rooms, located right in the heart of the Italian
        Dolomites. Imagine waking up to beautiful mountain views, spending your
        days exploring the dark forests around, or just relaxing in your private
        hot tub under the stars. Enjoy natures beauty in your own little home
        away from home. The perfect spot for a peaceful, calm vacation. Welcome
        to paradise.
      </p>
    </div>
  );
}
